#!/usr/bin/env python3
"""
artie_handoff.py — Bedrock Standard Session Handoff
Usage:
  python3 artie_handoff.py write "COMPLETED: X | FAILED: Y | NEXT: Z"
  python3 artie_handoff.py read
"""

import sys
import os
import json
import base64
import urllib.request
from datetime import datetime

CHECKPOINT_PATH = os.path.expanduser("~/.openclaw/workspace/ARTIE_LIVE_CHECKPOINT.md")
GITHUB_REPO = "Artemisclaws/sharedfolder"
GITHUB_PATH = "artie/ARTIE_LIVE_CHECKPOINT.md"

def get_pat():
    """Find PAT — check env var first, then file."""
    pat = os.environ.get("GITHUB_PAT") or os.environ.get("OPENCLAW_GITHUB_PAT")
    if pat:
        return pat
    for path in [
        os.path.expanduser("~/.openclaw/workspace/github_pat.txt"),
        os.path.expanduser("~/.openclaw/github_pat.txt"),
    ]:
        if os.path.exists(path):
            return open(path).read().strip()
    return None

def push_to_github(content, pat):
    """Push checkpoint to GitHub. Returns commit sha or None on failure."""
    try:
        headers = {"Authorization": f"token {pat}", "Accept": "application/vnd.github.v3+json"}
        # Get current sha
        req = urllib.request.Request(
            f"https://api.github.com/repos/{GITHUB_REPO}/contents/{GITHUB_PATH}",
            headers=headers
        )
        try:
            with urllib.request.urlopen(req) as r:
                sha = json.load(r)["sha"]
        except urllib.error.HTTPError as e:
            if e.code == 404:
                sha = None  # File doesn't exist yet
            else:
                raise
        payload = {
            "message": f"Artie handoff — {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "content": base64.b64encode(content.encode("utf-8")).decode("utf-8"),
        }
        if sha:
            payload["sha"] = sha
        req = urllib.request.Request(
            f"https://api.github.com/repos/{GITHUB_REPO}/contents/{GITHUB_PATH}",
            data=json.dumps(payload).encode("utf-8"),
            headers={**headers, "Content-Type": "application/json"},
            method="PUT"
        )
        with urllib.request.urlopen(req) as r:
            return json.load(r)["commit"]["sha"][:8]
    except Exception as e:
        return None

def write_checkpoint(status_line):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    date = datetime.now().strftime("%Y-%m-%d")

    # Parse status line
    parts = {}
    for chunk in status_line.split("|"):
        chunk = chunk.strip()
        if ":" in chunk:
            k, v = chunk.split(":", 1)
            parts[k.strip().upper()] = v.strip()

    completed = parts.get("COMPLETED", "not provided")
    failed = parts.get("FAILED", "none")
    next_task = parts.get("NEXT", "not specified")

    checkpoint = f"""# ARTIE LIVE CHECKPOINT
**Written:** {now}
**By:** Artie (artie_handoff.py)

---

## IF I COME BACK COLD — START HERE

1. Run SOP 01 — Soul Sync: `bash ~/.openclaw/workspace/sync_soul.sh`
2. Read this file: `cat {CHECKPOINT_PATH}`
3. Resume from **NEXT TASK** below
4. Do not start anything new until soul sync is confirmed

---

## THIS SESSION

**Date:** {date}
**Completed:** {completed}
**Failed:** {failed}
**Next task:** {next_task}

---

## CRON STATUS (auto-checked)
"""

    # Check cron
    import subprocess
    try:
        result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
        if "artie_report_sync" in result.stdout:
            checkpoint += "- artie_report_sync.py cron: ✅ present\n"
        else:
            checkpoint += "- artie_report_sync.py cron: ⚠️ MISSING — run SOP 03\n"
    except:
        checkpoint += "- Cron check: could not verify\n"

    # Check soul file timestamps
    checkpoint += "\n## SOUL FILE TIMESTAMPS (auto-checked)\n"
    soul_files = [
        "~/.openclaw/workspace/CLAUDE-CORE.md",
        "~/.openclaw/workspace/EMPIRE_STATUS.md",
        "~/.openclaw/workspace/SPRINT.md",
        "~/.openclaw/workspace/ARTIE-RUNBOOK.md",
    ]
    for sf in soul_files:
        path = os.path.expanduser(sf)
        if os.path.exists(path):
            ts = datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d %H:%M")
            checkpoint += f"- {os.path.basename(sf)}: last updated {ts}\n"
        else:
            checkpoint += f"- {os.path.basename(sf)}: ⚠️ NOT FOUND\n"

    checkpoint += f"\n---\n*Generated by artie_handoff.py — do not edit manually*\n"
    return checkpoint

def cmd_write(status_line):
    content = write_checkpoint(status_line)

    # Save locally
    os.makedirs(os.path.dirname(CHECKPOINT_PATH), exist_ok=True)
    with open(CHECKPOINT_PATH, "w") as f:
        f.write(content)
    print(f"Checkpoint written locally: {CHECKPOINT_PATH}")

    # Push to GitHub
    pat = get_pat()
    if pat:
        commit = push_to_github(content, pat)
        if commit:
            print(f"Pushed to GitHub: {commit}")
        else:
            print("GitHub push failed — checkpoint saved locally only. Flag for Claude.")
    else:
        print("No PAT found — checkpoint saved locally only. Set GITHUB_PAT env var to enable push.")

    print("\n--- CHECKPOINT PREVIEW ---")
    print(content)
    print("--- END ---")
    print("\nHandoff written. Done.")

def cmd_read():
    if os.path.exists(CHECKPOINT_PATH):
        with open(CHECKPOINT_PATH) as f:
            print(f.read())
    else:
        print("No checkpoint found. Starting cold.")
        print("Run SOP 01 — Soul Sync first: bash ~/.openclaw/workspace/sync_soul.sh")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage:")
        print('  python3 artie_handoff.py write "COMPLETED: X | FAILED: Y | NEXT: Z"')
        print("  python3 artie_handoff.py read")
        sys.exit(1)

    cmd = sys.argv[1].lower()
    if cmd == "write":
        if len(sys.argv) < 3:
            print('Error: write requires a status string.')
            print('Example: python3 artie_handoff.py write "COMPLETED: morning sync | FAILED: none | NEXT: evening wrap"')
            sys.exit(1)
        cmd_write(sys.argv[2])
    elif cmd == "read":
        cmd_read()
    else:
        print(f"Unknown command: {cmd}. Use 'read' or 'write'.")
        sys.exit(1)
